### ISSUE TITLE
add more countries

### ISSUE THREAD

**Issue by Raghavarya2002** [Raghavarya2002/worldTimeApp#1]

**Comment by z3n70** [comment]
@Raghavarya2002 i want to try fix this issues, could u assign me??

**Comment by Raghavarya2002** [comment]
yeah you can fix the issue 'add more countries' (assigned)

**Comment by REX51** [comment]
Hi @Raghavarya2002 I want to work on this, can you assign it to me?

**Comment by Raghavarya2002** [comment]
> @Raghavarya2002 i want to try fix this issues, could u assign me??

Any updates??

**Comment by Raghavarya2002** [comment]
> Hi @Raghavarya2002 I want to work on this, can you assign it to me?

this issue was assigned , if that person don't contribute , I'll definitely assign to you , so you can work on this issue..stay tuned

**Comment by Raghavarya2002** [comment]
> Hi @Raghavarya2002 I want to work on this, can you assign it to me?

hey , you can try this
