### ISSUE TITLE
change-background image

### ISSUE THREAD

**Issue by Raghavarya2002** [Raghavarya2002/worldTimeApp#2]

**Comment by AlecsisDuarte** [comment]
Hi @Raghavarya2002, 
I would like to give this one a try. 
Any particular image you would like me to use instead? Or more of a per location background?

**Comment by Raghavarya2002** [comment]
yeah sure and you can choose any image as per your choice (preferred-location background)

**Comment by AlecsisDuarte** [comment]
Added PR #3 let me know what do you think!

**Comment by Raghavarya2002** [comment]
> Added PR #3 let me know what do you think!

Great work👍
and please change text color and icon color according to the location , in some locations text is not visible due to white color , and in one location 'jakarta' image is not visible.

**Comment by AlecsisDuarte** [comment]
Sorry for my late response.
I was busy the last few days, but feel free to create the child issue and I'll be more than happy to pick it up.

I was planning to do some sort of a barely visible dark background under the text (for day backgrounds)  leveraging the [LinearGradient class](https://api.flutter.dev/flutter/painting/LinearGradient-class.html)

**Comment by Raghavarya2002** [comment]
> Sorry for my late response. I was busy the last few days, but feel free to create the child issue and I'll be more than happy to pick it up.
> 
> I was planning to do some sort of a barely visible dark background under the text (for day backgrounds) leveraging the [LinearGradient class](https://api.flutter.dev/flutter/painting/LinearGradient-class.html)

It's okay 
yeah you can definitely work on this project as much as you can , I'll definitely merge the PR after checking the code and app status :(
